title: The Meta-DAO
description: Docs explaining the Meta-DAO
theme: just-the-docs

#color_scheme: dark

url: https://metaDAOproject.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
